### ISSUE TITLE
Unable to deploy as stand alone or in PCF

### ISSUE THREAD

**Issue by er-avitesh** [pivotal-cf/PivotalMySQLWeb#1]
When i am trying to deploy as stand alone i am getting below error.

_Caused by: java.lang.ClassNotFoundException: javax.servlet.http.HttpSessionListener
        at java.base/java.net.URLClassLoader$1.run(Unknown Source) ~[na:na]
        at java.base/java.net.URLClassLoader$1.run(Unknown Source) ~[na:na]
        at java.base/java.security.AccessController.doPrivileged(Native Method) ~[na:na]
        at java.base/java.net.URLClassLoader.findClass(Unknown Source) ~[na:na]
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source) ~[na:na]
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:94) ~[PivotalMySQLWeb-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source) ~[na:na]
        at java.base/java.lang.Class.forName0(Native Method) ~[na:na]
        at java.base/java.lang.Class.forName(Unknown Source) ~[na:na]
        ... 41 common frames omitted
Caused by: java.util.zip.ZipException: invalid distance too far back
        at java.base/java.util.zip.InflaterInputStream.read(Unknown Source) ~[na:na]
        at org.springframework.boot.loader.jar.ZipInflaterInputStream.read(ZipInflaterInputStream.java:52) ~[PivotalMySQLWeb-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
        at java.base/jdk.internal.loader.Resource.getBytes(Unknown Source) ~[na:na]
        at java.base/java.net.URLClassLoader.defineClass(Unknown Source) ~[na:na]
        at java.base/java.net.URLClassLoader.access$100(Unknown Source) ~[na:na]
        ... 50 common frames omitted_

and when i am trying to push in my local PCF, i am getting below error.

 _Staging...
   warning [/tmp/app/BOOT-INF/lib/tomcat-embed-core-8.5.11.jar]:  804742 extra bytes at beginning or within zipfile
     (attempting to process anyway)
   warning [/tmp/app/BOOT-INF/lib/tomcat-embed-core-8.5.11.jar]:  804742 extra bytes at beginning or within zipfile
     (attempting to process anyway)
   -----> Java Buildpack Version: v3.13 (offline) | https://github.com/cloudfoundry/java-buildpack.git#03b493f
   -----> Downloading Open Jdk JRE 1.8.0_121 from https://java-buildpack.cloudfoundry.org/openjdk/trusty/x86_64/openjdk-1.8.0_121.tar.gz (found in cache)
          Expanding Open Jdk JRE to .java-buildpack/open_jdk_jre (1.3s)
   -----> Downloading Open JDK Like Memory Calculator 2.0.2_RELEASE from https://java-buildpack.cloudfoundry.org/memory-calculator/trusty/x86_64/memory-calculator-2.0.2_RELEASE.tar.gz (found in cache)
          Memory Settings: -Xms681574K -XX:MetaspaceSize=104857K -Xss349K -Xmx681574K -XX:MaxMetaspaceSize=104857K
   -----> Downloading Container Certificate Trust Store 2.0.0_RELEASE from https://java-buildpack.cloudfoundry.org/container-certificate-trust-store/container-certificate-trust-store-2.0.0_RELEASE.jar (found in cache)
          Adding certificates to .java-buildpack/container_certificate_trust_store/truststore.jks (0.9s)
   -----> Downloading Spring Auto Reconfiguration 1.10.0_RELEASE from https://java-buildpack.cloudfoundry.org/auto-reconfiguration/auto-reconfiguration-1.10.0_RELEASE.jar (found in cache)
   warning [/tmp/app/BOOT-INF/lib/tomcat-embed-core-8.5.11.jar]:  804742 extra bytes at beginning or within zipfile
     (attempting to process anyway)_

**Comment by papicella** [comment]
To run locally I use the following

$ mvn package
$ mvn spring-boot:run

Make sure you have JDK 1.8 in your classpath , I used this version and the maven version also shown. It should work and pushing to cloud foundry requires you yo package first and I tested this today and it works for me

pasapicella@pas-macbook:~/piv-projects/PivotalMySQLWeb$ java -version
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)

pasapicella@pas-macbook:~/piv-projects/PivotalMySQLWeb$ mvn --version
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-11T03:41:47+11:00)
Maven home: /usr/local/Cellar/maven/3.3.9/libexec
Java version: 1.8.0_91, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.13.2", arch: "x86_64", family: "mac"

**Comment by papicella** [comment]
If this still doesn't work please let me know
